name: Reusable Workflow With Outputs

on:
  workflow_call:
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.generatess_outputs.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.generate_outputs.outputs.output2 }}

jobs:
  generate_outputs:
    name: Generate outputs
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "firstword=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "secondword=world" >> $GITHUB_OUTPUT
