name: Reusable Workflow with Secrets

on:
  workflow_call:
    secrets:
      envPAT:
        required: true

jobs:
  reusable_with_password:
    runs-on: ubuntu-latest
    steps:
      - name: display conig path
        run: |
          echo ENV PATH secret: $(echo ${{ secrets.envPAT }} | base64)
