name: CI subdir

on:
  push:
    branches:
      - 'master'
    paths:
      - 'images/**'

jobs:
  build-subdirs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check file changed
        run: | 
          dirs=$(git diff --name-only HEAD^ HEAD | grep ^images/ | cut -d '/' -f 1-3 | sort | uniq)
          echo Directories with changes are: $dirs
          echo "Running Docker Containers Creation"
          for dir in $dirs; do
            cd $GITHUB_WORKSPACE/${dir}
            echo Running dockerbuild here: $(pwd)
          done

