name: CI subdir

on:
  push:
    branches:
      - 'master'
    paths:
      - 'images/**'

env:
  DOCKERHUB_REPO: yyovkov

jobs:
  build-subdirs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Check file changed
        run: | 
          dirs=$(git diff --name-only HEAD^ HEAD | grep ^images/ | cut -d '/' -f 1-3 | sort | uniq)
          echo Directories with changes are: $dirs
          echo "Running Docker Containers Creation"
          for dir in $dirs; do
            image=$(echo $dir | cut -d '/' -f 2)
            tag=$(echo $dir | cut -d '/' -f 3)
            cd $GITHUB_WORKSPACE/${dir}
            echo Running dockerbuild here: $(pwd)
            docker build -t ${DOCKERHUB_REPO}/${image}:${tag} .  -f Dockerfile
            docker tag ${DOCKERHUB_REPO}/${image}:${tag} ${DOCKERHUB_REPO}/${image}:latest
            docker push ${DOCKERHUB_REPO}/${image}:${tag}
            docker push ${DOCKERHUB_REPO}/${image}:latest
          done
