name: CI subdir

on:
  push:
    branches:
      - 'master'
    paths:
      - 'images/**'

jobs:
  build-subdirs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check file changed
        run: | 
          diff = $(git diff --name-only HEAD^ HEAD)
          echo Files changed are: $diff
